# Generated by Django 6.0.5 on 2026-05-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
